
import __ASTRO_IMAGE_IMPORT_1w7yYM from "../../assets/automatizacija-i-upravljanje.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fautomatizacija-i-upravljanje.md";
import __ASTRO_IMAGE_IMPORT_2rcrnk from "../../assets/automatska-klizna-kapija.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fugradnja-automatske-klizne-kapije.md";
import __ASTRO_IMAGE_IMPORT_1o0f2h from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkompletna-elektroinstalacija-stana.md";
import __ASTRO_IMAGE_IMPORT_1fbocy from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fugradnja-razvodnog-ormara-zgrade.md";
import __ASTRO_IMAGE_IMPORT_Z1FF3vk from "../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Finstalacija-gromobranske-zastite.md";
import __ASTRO_IMAGE_IMPORT_ZKMMmF from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Felektroinstalacije-poslovnog-prostora.md";
import __ASTRO_IMAGE_IMPORT_TdJCg from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frekonstrukcija-stare-elektroinstalacije.md";
import __ASTRO_IMAGE_IMPORT_Z2559NQ from "../../assets/elektroinstalacija-novogradnja.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Felektroinstalacija-novogradnja.md";
import __ASTRO_IMAGE_IMPORT_Z1mpMvG from "../../assets/led-rasvjeta-spusteni-plafon.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fugradnja-led-rasvjete-spusteni-plafon.md";
import __ASTRO_IMAGE_IMPORT_2wJqRA from "../../assets/polaganje-instalacijskih-cijevi.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpolaganje-instalacijskih-cijevi-novogradnja.md";
import __ASTRO_IMAGE_IMPORT_Z1grNCJ from "../../assets/sobni-termostat-ugradnja.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fugradnja-sobnog-termostata.md";
import __ASTRO_IMAGE_IMPORT_29YSUC from "../../assets/ugradnja-klima-uredjaja.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fugradnja-klima-uredjaja-porodicna-kuca.md";
export default new Map([["../../assets/automatizacija-i-upravljanje.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fautomatizacija-i-upravljanje.md", __ASTRO_IMAGE_IMPORT_1w7yYM], ["../../assets/automatska-klizna-kapija.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fugradnja-automatske-klizne-kapije.md", __ASTRO_IMAGE_IMPORT_2rcrnk], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkompletna-elektroinstalacija-stana.md", __ASTRO_IMAGE_IMPORT_1o0f2h], ["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fugradnja-razvodnog-ormara-zgrade.md", __ASTRO_IMAGE_IMPORT_1fbocy], ["../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Finstalacija-gromobranske-zastite.md", __ASTRO_IMAGE_IMPORT_Z1FF3vk], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Felektroinstalacije-poslovnog-prostora.md", __ASTRO_IMAGE_IMPORT_ZKMMmF], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frekonstrukcija-stare-elektroinstalacije.md", __ASTRO_IMAGE_IMPORT_TdJCg], ["../../assets/elektroinstalacija-novogradnja.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Felektroinstalacija-novogradnja.md", __ASTRO_IMAGE_IMPORT_Z2559NQ], ["../../assets/led-rasvjeta-spusteni-plafon.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fugradnja-led-rasvjete-spusteni-plafon.md", __ASTRO_IMAGE_IMPORT_Z1mpMvG], ["../../assets/polaganje-instalacijskih-cijevi.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpolaganje-instalacijskih-cijevi-novogradnja.md", __ASTRO_IMAGE_IMPORT_2wJqRA], ["../../assets/sobni-termostat-ugradnja.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fugradnja-sobnog-termostata.md", __ASTRO_IMAGE_IMPORT_Z1grNCJ], ["../../assets/ugradnja-klima-uredjaja.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fugradnja-klima-uredjaja-porodicna-kuca.md", __ASTRO_IMAGE_IMPORT_29YSUC]]);
		